version: '3.7'

services:
  app:
    build: ./backend/
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      expose:
        - '3306'