version: '3.7'

services:
  node:
    build: ./backend/
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: on-failure
  app:
    build: ./soccer-league/
    ports:
      - '80:80'
    depends_on:
      - node
    restart: on-failure
    links:
      - node
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'